Update mavn.yml

diff --git a/.github/workflows/mavn.yml b/.github/workflows/mavn.yml
--- a/.github/workflows/mavn.yml
+++ b/.github/workflows/mavn.yml
@@ -6,7 +6,7 @@ on:
 
 jobs:
   build:
-    runs-on: ubuntu-latest
+    runs-on: [self-hosted, linux]
 
     steps:
       # 1. Checkout code
@@ -19,6 +19,17 @@ jobs:
         with:
           distribution: 'temurin'
           java-version: '17'
+
+      # 3. Install Maven if missing
+      - name: Ensure Maven is installed
+        run: |
+          if ! command -v mvn &> /dev/null; then
+            echo "Maven not found. Installing..."
+            sudo dnf install -y maven
+          else
+            echo "Maven is already installed"
+          fi
+          mvn -version
 
       # 3. Build with Maven
       - name: Build with Maven
